stages:
  - lint
  - vulnerabilities_trivy
  - vulnerabilities_sbom_syft_grype

default:
  image: ubuntu:24.04

helm_lint:
  stage: lint
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo 'Starting env prep for testing...';
    - apt-get update;
    - apt-get install curl gpg apt-transport-https --yes;
    - curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null;
    - echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | tee /etc/apt/sources.list.d/helm-stable-debian.list;
    - apt-get update;
    - apt-get install helm;
    - helm version;
    - helm package ./super-chart --destination ./release;
    - find ./release -name "*super-chart*.tgz" -exec helm lint --strict --values values-tests.yaml {} \;
    - find ./release -name "*super-chart*.tgz" -exec helm template --debug --values values-tests.yaml {} \;
    - find ./release -name "*super-chart*.tgz" -exec rm -rf {} \;
    - find ./docs -name "*super-chart*.tgz" -exec helm lint --strict --values values-tests.yaml {} \;
    - find ./docs -name "*super-chart*.tgz" -exec helm template --debug --values values-tests.yaml {} \;

vulnerabilities_trivy:
  stage: vulnerabilities_trivy
  script:
    - echo 'Starting tests...'
    - apt update && apt install -y gnupg curl wget unzip ca-certificates
    - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null
    - echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | tee -a /etc/apt/sources.list.d/trivy.list
    - apt-get update
    - apt-get install trivy -y
    - trivy fs $CI_PROJECT_DIR --include-dev-deps --dependency-tree

vulnerabilities_sbom_syft_grype:
  stage: vulnerabilities_sbom_syft_grype
  script:
    - echo 'Starting tests...'
    - apt update && apt install -y gnupg curl wget unzip ca-certificates
    - curl -sSfL https://get.anchore.io/syft | sh -s -- -b /usr/local/bin
    - curl -sSfL https://get.anchore.io/grype | sh -s -- -b /usr/local/bin
    - rm -rf /scans || true
    - mkdir /scans
    - syft $CI_PROJECT_DIR -o cyclonedx-json=/scans/sbom.json
    - grype sbom:/scans/sbom.json
