# Default values for game-2048.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "game"

imagePullSecrets: []

nameOverride: ""

fullnameOverride: "game-2048"

secrets:
  - name: env-secret
    type: env
    variables:
      environment: DEV
      ALLOY_OTLP_UPSTREAM: tempo:4317
      ALLOY_OTLP_LOGS_UPSTREAM: "http://loki:3100/otlp"

deployments:
  - name: "backend"
    kind: DaemonSet
    replicaCount: 1
    initContainers:
      - name: init
        image: busybox:latest
        command: ["sh", "-c", "chown 10001:10001 /var/tempo"]
        volumeMounts:
          - mountPath: /var/tempo
            name: data-volume
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
    containers:
      - name: "api"
        envFrom:
          - secretRef:
              name: env-secret
        startup:
          enabled: false
          command: []
          args: []
        targetGroupBinding:
          enabled: false
          arn: ""
          securityGroup: ""
        image:
          repository: public.ecr.aws/l6m2t8p7/docker-2048
          pullPolicy: IfNotPresent
          tag: "latest"
        podAnnotations: {}
        podLabels: {}
        podSecurityContext: {}
        securityContext: {}
        service:
          enabled: true
          scheme: internal
          type: ClusterIP
          port: 80
          extraPorts:
            - name: oltp
              enabled: true
              port: 4317
              protocol: TCP
            - name: delve
              enabled: true
              port: 2345
              protocol: TCP
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        ingress:
          enabled: false
          className: ""
          annotations: {}
          hosts:
            - host: game-2048.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
        httpRoute:
          enabled: false
          annotations: {}
          parentRefs:
            - name: gateway
              sectionName: http
          hostnames:
            - game-2048.local
          rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /headers
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts: []

    serviceAccount:
      create: true
      automount: false
      annotations: {}
      name: "game-2048-service-account"

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    volumes: []

    nodeSelector: {}

    tolerations: []

    volumeClaimTemplates:
      name: ""
      storageClassName: ""
      storage: ""

    affinity:
      enabled: true
