# Default values for super-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "test"

imagePullSecrets:
  - test

nameOverride: ""

fullnameOverride: "test"

secrets:
  - name: env-secret
    type: env
    variables:
      environment: DEV
  - name: file-secret
    type: file
    files:
      config.json: configuration.json

deployments:
  - name: "frontend"
    kind: Deployment
    replicaCount: 1
    containers:
      - name: "worker"
        startup:
          enabled: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt update;
              apt install unzip -y;
              apt install curl -y;
              apt install -y less;
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
              unzip awscliv2.zip;
              ./aws/install;
              while true; do date +'%Y-%m-%d %H:%M:%S'; sleep 10;done
        targetGroupBinding:
          enabled: false
          arn: ""
          securityGroup: ""
        image:
          repository: nginx
          pullPolicy: IfNotPresent
          tag: "latest"
        podAnnotations: {}
        podLabels: {}
        podSecurityContext: {}
        securityContext: {}
        service:
          scheme: internal
          type: ClusterIP
          port: 80
          extraPorts:
            - name: https
              enabled: false
              port: 443
              protocol: TCP
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        ingress:
          enabled: false
          className: "alb"
          annotations:
            # alb.ingress.kubernetes.io/certificate-arn: arn:...
            # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
            # alb.ingress.kubernetes.io/ssl-redirect: "443"
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/healthcheck-path: /
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: nginx.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
        httpRoute:
          enabled: false
          annotations: {}
          parentRefs:
            - name: gateway
              sectionName: http
          hostnames:
            - nginx.local
          rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /headers
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts: []

      - name: "api"
        # startup:
        #   enabled: false
        #   command: ["/bin/sh", "-c"]
        #   args:
        #     - |
        #       echo "Starting application...";
        targetGroupBinding:
          enabled: true
          arn: "test"
          securityGroup: "test"
        image:
          repository: "test"
          pullPolicy: IfNotPresent
          tag: "test"
        podAnnotations: {}
        podLabels: {}
        podSecurityContext: {}
        securityContext: {}
        service:
          scheme: internal
          type: ClusterIP
          port: 80
          extraPorts:
            - name: https
              enabled: false
              port: 443
              protocol: TCP
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        ingress:
          enabled: true
          className: "alb"
          annotations:
            alb.ingress.kubernetes.io/certificate-arn: arn:...
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
            alb.ingress.kubernetes.io/ssl-redirect: "443"
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/healthcheck-path: /
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - host: super-chart.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
        httpRoute:
          enabled: true
          annotations: {}
          parentRefs:
            - name: gateway
              sectionName: http
          hostnames:
            - super-chart.local
          rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /headers
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - name: config
            mountPath: "/etc/nginx/conf.d"
            readOnly: false
          - name: template
            mountPath: "/usr/share/nginx/html"
            readOnly: false

    serviceAccount:
      create: true
      automount: false
      annotations: {}
      name: "test"

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    volumes:
      - name: config
        secret:
          secretName: nginx-custom-config
          optional: false
      - name: template
        secret:
          secretName: nginx-custom-template
          optional: false

    nodeSelector: {}

    tolerations: []

    volumeClaimTemplates:
      name: "data"
      storageClassName: "gp3"
      storage: "100Gi"

    affinity:
      enabled: false

  # - name: "backend"
  #   kind: Deployment
  #   replicaCount: 1
  #   containers:
  #     - name: "worker"
  #       startup:
  #         enabled: true
  #         command: ["/bin/sh", "-c"]
  #         args:
  #           - |
  #             apt update;
  #             apt install unzip -y;
  #             apt install curl -y;
  #             apt install -y less;
  #             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
  #             unzip awscliv2.zip;
  #             ./aws/install;
  #             while true; do date +'%Y-%m-%d %H:%M:%S'; sleep 10;done
  #       targetGroupBinding:
  #         enabled: false
  #         arn: ""
  #         securityGroup: ""
  #       image:
  #         repository: nginx
  #         pullPolicy: IfNotPresent
  #         tag: "latest"
  #       podAnnotations: {}
  #       podLabels: {}
  #       podSecurityContext: {}
  #       securityContext: {}
  #       service:
  #         scheme: internal
  #         type: ClusterIP
  #         port: 80
  #         extraPorts:
  #           - name: https
  #             enabled: false
  #             port: 443
  #             protocol: TCP
  #         annotations:
  #           service.beta.kubernetes.io/aws-load-balancer-type: external
  #           service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  #           service.beta.kubernetes.io/aws-load-balancer-scheme: internal
  #           # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  #       ingress:
  #         enabled: false
  #         className: "alb"
  #         annotations:
  #           # alb.ingress.kubernetes.io/certificate-arn: arn:...
  #           # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #           # alb.ingress.kubernetes.io/ssl-redirect: "443"
  #           alb.ingress.kubernetes.io/scheme: internet-facing
  #           alb.ingress.kubernetes.io/target-type: ip
  #           alb.ingress.kubernetes.io/healthcheck-path: /
  #           # kubernetes.io/ingress.class: nginx
  #           # kubernetes.io/tls-acme: "true"
  #         hosts:
  #           - host: nginx.local
  #             paths:
  #               - path: /
  #                 pathType: ImplementationSpecific
  #         tls: []
  #       httpRoute:
  #         enabled: false
  #         annotations: {}
  #         parentRefs:
  #           - name: gateway
  #             sectionName: http
  #         hostnames:
  #           - nginx.local
  #         rules:
  #           - matches:
  #             - path:
  #                 type: PathPrefix
  #                 value: /headers
  #       resources:
  #         requests:
  #           cpu: 100m
  #           memory: 128Mi
  #       livenessProbe:
  #         exec:
  #           command:
  #             - whoami
  #         initialDelaySeconds: 15
  #         periodSeconds: 20
  #       readinessProbe:
  #         exec:
  #           command:
  #             - whoami
  #         initialDelaySeconds: 15
  #         periodSeconds: 20
  #       volumeMounts: []

  #     - name: "api"
  #       # startup:
  #       #   enabled: false
  #       #   command: ["/bin/sh", "-c"]
  #       #   args:
  #       #     - |
  #       #       echo "Starting application...";
  #       targetGroupBinding:
  #         enabled: true
  #         arn: "test"
  #         securityGroup: "test"
  #       image:
  #         repository: "test"
  #         pullPolicy: IfNotPresent
  #         tag: "test"
  #       podAnnotations: {}
  #       podLabels: {}
  #       podSecurityContext: {}
  #       securityContext: {}
  #       service:
  #         scheme: internal
  #         type: ClusterIP
  #         port: 80
  #         extraPorts:
  #           - name: https
  #             enabled: false
  #             port: 443
  #             protocol: TCP
  #         annotations:
  #           service.beta.kubernetes.io/aws-load-balancer-type: external
  #           service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  #           service.beta.kubernetes.io/aws-load-balancer-scheme: internal
  #           service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  #       ingress:
  #         enabled: true
  #         className: "alb"
  #         annotations:
  #           alb.ingress.kubernetes.io/certificate-arn: arn:...
  #           alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  #           alb.ingress.kubernetes.io/ssl-redirect: "443"
  #           alb.ingress.kubernetes.io/scheme: internet-facing
  #           alb.ingress.kubernetes.io/target-type: ip
  #           alb.ingress.kubernetes.io/healthcheck-path: /
  #           kubernetes.io/ingress.class: nginx
  #           kubernetes.io/tls-acme: "true"
  #         hosts:
  #           - host: super-chart.local
  #             paths:
  #               - path: /
  #                 pathType: ImplementationSpecific
  #         tls: []
  #       httpRoute:
  #         enabled: true
  #         annotations: {}
  #         parentRefs:
  #           - name: gateway
  #             sectionName: http
  #         hostnames:
  #           - super-chart.local
  #         rules:
  #           - matches:
  #             - path:
  #                 type: PathPrefix
  #                 value: /headers
  #       resources:
  #         requests:
  #           cpu: 500m
  #           memory: 512Mi
  #       livenessProbe:
  #         exec:
  #           command:
  #             - whoami
  #         initialDelaySeconds: 15
  #         periodSeconds: 20
  #       readinessProbe:
  #         exec:
  #           command:
  #             - whoami
  #         initialDelaySeconds: 15
  #         periodSeconds: 20
  #       volumeMounts:
  #         - name: config
  #           mountPath: "/etc/nginx/conf.d"
  #           readOnly: false
  #         - name: template
  #           mountPath: "/usr/share/nginx/html"
  #           readOnly: false

  #   serviceAccount:
  #     create: true
  #     automount: false
  #     annotations: {}
  #     name: "test"

  #   autoscaling:
  #     enabled: true
  #     minReplicas: 1
  #     maxReplicas: 100
  #     targetCPUUtilizationPercentage: 80
  #     targetMemoryUtilizationPercentage: 80

  #   volumes:
  #     - name: config
  #       secret:
  #         secretName: nginx-custom-config
  #         optional: false
  #     - name: template
  #       secret:
  #         secretName: nginx-custom-template
  #         optional: false

  #   nodeSelector: {}

  #   tolerations: []

  #   volumeClaimTemplates:
  #     name: "data"
  #     storageClassName: "gp3"
  #     storage: "100Gi"

  #   affinity:
  #     enabled: false
