# Default values for super-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: ""

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

secrets: []
  # - name: env-secret
  #   type: env
  #   variables:
  #     environment: DEV
  # - name: file-secret
  #   type: file
  #   files:
  #     config.json: configuration.json

deployments:
  - name: ""
    kind: Deployment
    replicaCount: 1
    containers:
      - name: ""
        # startup:
        #   enabled: false
        #   command: ["/bin/sh", "-c"]
        #   args:
        #     - |
        #       echo "Starting application...";
        targetGroupBinding:
          enabled: false
          arn: ""
          securityGroup: ""
        image:
          repository: ""
          pullPolicy: IfNotPresent
          tag: ""
        podAnnotations: {}
        podLabels: {}
        podSecurityContext: {}
        securityContext: {}
        service:
          scheme: internal
          type: ClusterIP
          port: 80
          extraPorts:
            - name: https
              enabled: false
              port: 443
              protocol: TCP
          annotations: {}
            # service.beta.kubernetes.io/aws-load-balancer-type: external
            # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            # service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .service.scheme | default "internal" }}
            # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        ingress:
          enabled: false
          className: ""
          annotations: {}
          hosts:
            - host: super-chart.local
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
        httpRoute:
          enabled: false
          annotations: {}
          parentRefs:
            - name: gateway
              sectionName: http
          hostnames:
            - super-chart.local
          rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /headers
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
              - whoami
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts: []

    serviceAccount:
      create: true
      automount: false
      annotations: {}
      name: ""

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    volumes: []

    nodeSelector: {}

    tolerations: []

    volumeClaimTemplates:
      name: ""
      storageClassName: ""
      storage: ""

    affinity:
      enabled: false
