{{/* 
  GLOBAL 
*/}}
{{- $global := .Values -}}
{{- $fullName := include "super-chart.fullname" . -}}
{{- $appName := include "super-chart.name" . -}}
{{- $chart := include "super-chart.chart" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{/*
  TEMPLATE
*/}}
{{- if hasKey .Values "deployments" }}
  {{- range .Values.deployments }}
    {{- $deployment := . -}}
apiVersion: apps/v1
kind: {{ .kind | default "Deployment" }}
metadata:
  name: {{ $fullName }}{{ printf "-%s" .name }}
  namespace: {{ $global.namespace | default "dev" }}
  labels:
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" .name }}
    app.kubernetes.io/instance: {{ $releaseName }}
    {{- if $chartAppVersion }}
    app.kubernetes.io/version: {{ $chartAppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
spec:
  {{- if hasKey . "autoscaling" }}
    {{- if hasKey .autoscaling "enabled" }}
      {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
      {{- end }}
    {{- else }}
  replicas: {{ .replicaCount }}
    {{- end }}
  {{- else }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" .name }}
      app.kubernetes.io/instance: {{ $releaseName }}
  {{- if eq .kind "StatefulSet" }}
  minReadySeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: {{ .volumeClaimTemplates.name | default "data" }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .volumeClaimTemplates.storageClassName | default "gp3" }}
        resources:
          requests:
            storage: {{ .volumeClaimTemplates.storage | default "1Gi" }}
  {{- end }}
  template:
    metadata:
      {{- if hasKey . "podAnnotations" }}
        {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        helm.sh/chart: {{ $chart }}
        app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" .name }}
        app.kubernetes.io/instance: {{ $releaseName }}
        {{- if $chartAppVersion }}
        app.kubernetes.io/version: {{ $chartAppVersion | quote }}
        {{- end }}
        app.kubernetes.io/managed-by: {{ $releaseService }}
        {{- if hasKey . "podLabels" }}
          {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
    spec:
      {{- with $global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $fullName }}{{ printf "-%s" .name }}
      {{- if hasKey . "podSecurityContext" }}
        {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if hasKey . "containers" }}
      containers:
        {{- range .containers }}
        - name: {{ $fullName }}{{ printf "-%s" $deployment.name }}{{ printf "-%s" .name }}
          {{- if hasKey . "securityContext" }}
            {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          image: "{{ .image.repository }}:{{ .image.tag | default $chartVersion }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
            {{- if hasKey .service "extraPorts" }}
              {{- range .service.extraPorts }}
                {{- if hasKey . "enabled" }}
                  {{- if .enabled }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- if hasKey . "livenessProbe" }}
            {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if hasKey . "readinessProbe" }}
            {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
          {{- if hasKey . "resources" }}
            {{- with .resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            requests:
              cpu: 250m
              memory: 256Mi
          {{- end }}
          {{- if hasKey . "volumeMounts" }}
            {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if hasKey . "volumes" }}
        {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if hasKey . "nodeSelector" }}
        {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if hasKey . "affinity" }}
        {{- if hasKey .affinity "enabled" }}
          {{- if .affinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                      - {{ $fullName }}{{ printf "-%s" .name }}
              topologyKey: "kubernetes.io/hostname"
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if hasKey . "tolerations" }}
        {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{/*
  END TEMPLATE
*/}}
