{{/* 
  GLOBAL 
*/}}
{{- $global := .Values -}}
{{- $fullName := include "super-chart.fullname" . -}}
{{- $appName := include "super-chart.name" . -}}
{{- $chart := include "super-chart.chart" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{/*
  TEMPLATE
*/}}
{{- if hasKey .Values "deployments" }}
  {{- range .Values.deployments }}
    {{- $deployment := . -}}
    {{- if hasKey . "containers" }}
      {{- range .containers }}
        {{- $container := . -}}
        {{- $svcPort := .service.port -}}
        {{- if hasKey . "httpRoute" }}
          {{- if hasKey .httpRoute "enabled" }}
            {{- if .httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $chartName }}{{ printf "-%s" .name | default "" }}
  namespace: {{ $global.namespace | default "dev" }}
  labels:
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" $deployment.name | default "" }}
    app.kubernetes.io/instance: {{ $releaseName }}
    {{- if $chartAppVersion }}
    app.kubernetes.io/version: {{ $chartAppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
  {{- if hasKey .httpRoute "annotations" }}
    {{- with .httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
    {{- with .httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .httpRoute.rules }}
      {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ $chartName }}{{ printf "-%s" $container.name | default "" }}
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{/*
  END TEMPLATE
*/}}
