{{/* 
  GLOBAL 
*/}}
{{- $global := .Values -}}
{{- $fullName := include "super-chart.fullname" . -}}
{{- $appName := include "super-chart.name" . -}}
{{- $chart := include "super-chart.chart" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{/*
  TEMPLATE
*/}}
{{- if hasKey .Values "secrets" }}
  {{- range .Values.secrets }}
    {{- if hasKey . "type" }}
      {{- if .type }}
        {{- if eq .type "file" }}
          {{- if hasKey . "files" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $global.namespace | default "dev" }}
  labels:
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" .name | default "" }}
    app.kubernetes.io/instance: {{ $releaseName }}
    {{- if $chartAppVersion }}
    app.kubernetes.io/version: {{ $chartAppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
type: "opaque"
data:
  {{- range $name, $content := .files }}
  {{ $name }}: {{ $content | b64enc | quote }}
  {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{/*
  END TEMPLATE
*/}}
