{{- if .Values.targetGroupBinding.enabled }}
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/targetgroupbinding/spec
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "super-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "game" }}
spec:
  serviceRef:
    name: {{ include "super-chart.fullname" . }}
    port: {{ .Values.service.port }}
  networking:
    ingress:
      - from:
          - securityGroup: 
              groupID: {{ .Values.targetGroupBinding.securityGroup }}
        ports:
          - port: http
            protocol: TCP
          - port: {{ .Values.service.port }}
            protocol: TCP
  targetType: ip
  targetGroupARN: {{ .Values.targetGroupBinding.arn }}
{{- end }}
