{{/* 
  GLOBAL 
*/}}
{{- $global := .Values -}}
{{- $fullName := include "super-chart.fullname" . -}}
{{- $appName := include "super-chart.name" . -}}
{{- $chart := include "super-chart.chart" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{/*
  TEMPLATE
*/}}
{{- if hasKey .Values "deployments" }}
  {{- range $deployment := .Values.deployments }}
    {{- with $deployment }}
      {{- if hasKey . "containers" }}
        {{- range $container := .containers }}
          {{- with $container }}
            {{- $svcPort := .service.port -}}
            {{- if hasKey . "ingress" }}
              {{- if hasKey .ingress "enabled" }}
                {{- if .ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}{{ printf "-%s" $deployment.name }}{{ printf "-%s" .name }}
  namespace: {{ $global.namespace | default "dev" }}
  labels:
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" $deployment.name }}
    app.kubernetes.io/instance: {{ $releaseName }}
    {{- if $chartAppVersion }}
    app.kubernetes.io/version: {{ $chartAppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
  {{- if hasKey .ingress "annotations" }}
    {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with .ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .ingress.tls }}
  tls:
    {{- range .ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}{{ printf "-%s" $deployment.name }}{{ printf "-%s" $container.name }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{/*
  END TEMPLATE
*/}}
