{{/* 
  GLOBAL 
*/}}
{{- $global := .Values -}}
{{- $fullName := include "super-chart.fullname" . -}}
{{- $appName := include "super-chart.name" . -}}
{{- $chart := include "super-chart.chart" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{/*
  TEMPLATE
*/}}
{{- if hasKey .Values "secrets" }}
  {{- range .Values.secrets }}
    {{- if hasKey . "type" }}
      {{- if .type }}
        {{- if eq .type "env" }}
          {{- if hasKey . "variables" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $global.namespace | default "dev" }}
type: "opaque"
data:
  {{- range $name, $value := .variables }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{/*
  END TEMPLATE
*/}}
