{{/* 
  GLOBAL 
*/}}
{{- $global := .Values -}}
{{- $fullName := include "super-chart.fullname" . -}}
{{- $appName := include "super-chart.name" . -}}
{{- $chart := include "super-chart.chart" . -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{/*
  TEMPLATE
*/}}
{{- if hasKey .Values "deployments" }}
  {{- range $deployment := .Values.deployments }}
    {{- with $deployment }}
      {{- if hasKey . "serviceAccount" }}
        {{- if hasKey .serviceAccount "create" }}
          {{- if .serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name | default (printf "%s-%s" $fullName .name) }}
  namespace: {{ $global.namespace | default "dev" }}
  labels:
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/name: {{ $fullName }}{{ printf "-%s" .name }}
    app.kubernetes.io/instance: {{ $releaseName }}
    {{- if $chartAppVersion }}
    app.kubernetes.io/version: {{ $chartAppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .serviceAccount.automount }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{/*
  END TEMPLATE
*/}}
